CREATE TABLE TARIF (
  CodeTarif INT NOT NULL PRIMARY KEY,
  PrixsemHS FLOAT NOT NULL,
  PrixSemBS FLOAT NOT NULL
);

CREATE TABLE APPARTEMENT (
  NumLocation INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Categorie VARCHAR(50) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  NbPersonnes INT NOT NULL,
  AdresseLocation VARCHAR(255) NOT NULL,
  photo LONGBLOB NOT NULL,
  Equipements VARCHAR(255) NOT NULL,
  CodeTarif INT NOT NULL,
  Num INT NOT NULL,
  FOREIGN KEY (CodeTarif) REFERENCES TARIF(CodeTarif),
  FOREIGN KEY (Num) REFERENCES PROPRIETAIRE(Num)
);

CREATE TABLE PROPRIETAIRE (
  Num INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nom VARCHAR(50) NOT NULL,
  Prenom VARCHAR(50) NOT NULL,
  Adresse1 VARCHAR(255) NOT NULL,
  Adresse2 VARCHAR(255),
  CodePostal VARCHAR(10) NOT NULL,
  Ville VARCHAR(50) NOT NULL,
  NumTel2 VARCHAR(20),
  NumTel1 VARCHAR(20),
  CAcumule FLOAT NOT NULL,
  Email VARCHAR(50) NOT NULL
);

CREATE TABLE CONTRAT (
  NumContrat INT NOT NULL PRIMARY KEY,
  Etat VARCHAR(50) NOT NULL,
  DateCreation DATE NOT NULL,
  DateDebut DATE NOT NULL,
  Datefin DATE NOT NULL,
  NumLocation INT NOT NULL,
  NumLocataire INT NOT NULL,
  FOREIGN KEY (NumLocation) REFERENCES APPARTEMENT(NumLocation),
  FOREIGN KEY (NumLocataire) REFERENCES LOCATAIRE(NumLocataire)
);

CREATE TABLE LOCATAIRE (
  NumLocataire INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NomLocataire VARCHAR(50) NOT NULL,
  PrenomLocataire VARCHAR(50) NOT NULL,
  Adresse1Locataire VARCHAR(255) NOT NULL,
  Adresse2Locataire VARCHAR(255),
  CodePostalLocataire VARCHAR(10) NOT NULL,
  VilleLocataire VARCHAR(50) NOT NULL,
  NumTel2Locataire VARCHAR(20),
  NumTel1Locataire VARCHAR(20),
  EmailLocataire VARCHAR(50) NOT NULL
);

